// regulate-polyvagal.timing.js - one clock for picture + score, cued to the narration.
// Needs lib/timing-kit.js and regulate-polyvagal.vo.js (generated by bin/vo-words.py) first.
// Every cue is a spoken word: cue(seg, phrase) = the ms the phrase's first word starts, so a
// re-voiced narration re-times the whole film without touching a number here.
var TIMING = (function () {
  const V = VO;
  const norm = (s) => s.toLowerCase().replace(/[’]/g, "'").replace(/[^a-z0-9']/g, '');
  function find(seg, phrase, n) {
    const ws = V.words.filter((w) => w.seg.startsWith(seg));
    const ph = phrase.split(/\s+/).map(norm).filter(Boolean);
    let hits = 0;
    for (let i = 0; i + ph.length <= ws.length; i++) {
      if (ph.every((p, k) => norm(ws[i + k].w) === p) && hits++ === n) return [ws[i], ws[i + ph.length - 1]];
    }
    throw new Error(`cue not found: ${seg} "${phrase}" #${n}`);
  }
  const cue = (seg, phrase, n = 0) => find(seg, phrase, n)[0].s;
  const cueEnd = (seg, phrase, n = 0) => find(seg, phrase, n)[1].e;
  const S = {}; for (const s of V.segments) S[s.id.slice(0, 3)] = s;
  const T = { cue, cueEnd, S, words: V.words, voDur: V.durMs };
  const c = (T.c = {});

  // s01 hook
  c.pound = cue('s01', 'Your heart'); c.wrong = cue('s01', 'and nothing is wrong');
  c.numb = cue('s01', 'Or you feel'); c.move = cue('s01', "and you can't make");
  c.flaw = cue('s01', 'Neither one'); c.both = cue('s01', 'Both are');
  // s02 question
  c.q = S.s02.startMs; c.asking = cue('s02', 'asking'); c.safe = cue('s02', 'Am I safe');
  c.porges = cue('s02', 'Stephen Porges'); c.neuro = cue('s02', 'neuroception');
  c.below = cue('s02', 'below awareness'); c.faster = cue('s02', 'faster than thinking');
  c.sets = cue('s02', 'It sets your state');
  // s03 map
  c.theory = S.s03.startMs; c.model = cue('s03', "It's a model"); c.debated = cue('s03', 'still debated');
  c.reading = cue('s03', 'as a way of reading');
  // s04 vagus
  c.vagus = S.s04.startMs; c.wander = cue('s04', 'means wandering'); c.runs = cue('s04', 'It runs from');
  c.heart4 = cue('s04', 'past your heart'); c.lungs = cue('s04', 'and lungs'); c.gut = cue('s04', 'your gut');
  c.poly = cue('s04', 'Poly means many'); c.split = cue('s04', 'two branches'); c.newer = cue('s04', 'a newer one');
  c.older = cue('s04', 'an older one'); c.traffic = cue('s04', 'most of the'); c.upward = cue('s04', 'runs upward');
  c.reports = cue('s04', 'Your body reports'); c.bodyFirst = cue('s04', 'body-first');
  // s05 ladder
  c.ladder = S.s05.startMs; c.asLadder = cue('s05', 'as a ladder'); c.top = cue('s05', 'At the top');
  c.middle = cue('s05', 'In the middle'); c.bottom = cue('s05', 'At the bottom'); c.threat = cue('s05', 'Under threat');
  c.drop = cue('s05', 'drop down'); c.rung1 = cue('s05', 'one rung'); c.rung2 = cue('s05', 'at a time');
  // s06 ventral
  c.ventral = S.s06.startMs; c.vv = cue('s06', 'ventral vagal'); c.think = cue('s06', 'think connect');
  c.breath6 = cue('s06', 'Your breath'); c.face = cue('s06', 'Your face'); c.voice6 = cue('s06', 'your voice has');
  c.stress6 = cue('s06', 'You can still feel'); c.takeover = cue('s06', "It just doesn't");
  // s07 sympathetic
  c.symp = S.s07.startMs; c.heart7 = cue('s07', 'Your heart'); c.breath7 = cue('s07', 'Breath rises');
  c.muscles = cue('s07', 'Muscles brace'); c.jaw = cue('s07', 'the jaw sets'); c.hands = cue('s07', 'your hands go');
  c.vision = cue('s07', 'Your vision'); c.thoughts = cue('s07', 'your thoughts start');
  c.faces = cue('s07', 'It has two faces'); c.flight = cue('s07', 'Flight feels'); c.restless = cue('s07', 'restless');
  c.wired = cue('s07', 'wired'); c.exit = cue('s07', 'scanning for the exit'); c.fight = cue('s07', 'Fight feels');
  c.heat = cue('s07', 'heat'); c.pressure = cue('s07', 'pressure'); c.fuse = cue('s07', 'a short fuse');
  c.settles = cue('s07', 'Energy that finishes'); c.settled = cue('s07', 'settles'); c.stuck = cue('s07', 'Energy with nowhere');
  c.stuckEnd = cue('s07', 'keeps you stuck');
  // s08 dorsal
  c.dorsal = S.s08.startMs; c.dv = cue('s08', 'dorsal vagal'); c.plug = cue('s08', 'pulls the plug');
  c.drops = cue('s08', 'Energy drops'); c.limbs = cue('s08', 'Your limbs'); c.flat = cue('s08', 'your voice goes flat');
  c.far = cue('s08', 'The world feels'); c.foggy = cue('s08', 'foggy'); c.lazy = cue('s08', "This isn't laziness");
  c.protect = cue('s08', "It's protection"); c.saving = cue('s08', 'Your body is saving'); c.switchOff = cue('s08', 'a full switch-off');
  c.braced = cue('s08', "Sometimes you're braced"); c.cantMove = cue('s08', "and still can't move");
  c.freeze = cue('s08', 'Regulate calls'); c.freezeWord = cue('s08', 'Freeze');
  // s10 window
  c.window = S.s10.startMs; c.wot = cue('s10', 'window of tolerance'); c.inside = cue('s10', 'Inside the window');
  c.straight = cue('s10', 'think straight'); c.above = cue('s10', 'Above it'); c.muchCharge = cue('s10', 'too much charge');
  c.belowW = cue('s10', 'Below it'); c.little = cue('s10', 'too little'); c.notFixed = cue('s10', "The window isn't fixed");
  c.narrows = cue('s10', 'It narrows'); c.widen = cue('s10', 'it can widen');
  // s11 spot
  c.spot = S.s11.startMs; c.three = cue('s11', 'Check three things'); c.cBreath = cue('s11', 'Breath');
  c.b0 = cue('s11', 'slow and low'); c.b1 = cue('s11', 'fast and high'); c.b2 = cue('s11', 'or barely there');
  c.cEnergy = cue('s11', 'Energy'); c.e0 = cue('s11', 'steady'); c.e1 = cue('s11', 'buzzing'); c.e2 = cue('s11', 'or drained');
  c.cConn = cue('s11', 'Connection'); c.k0 = cue('s11', 'can you take in'); c.k1 = cue('s11', 'too loud'); c.k2 = cue('s11', 'too far away');
  c.sure = cue('s11', "You don't need"); c.guess = cue('s11', 'A rough guess');
  // s12 match
  c.match = S.s12.startMs; c.activated = cue('s12', "If you're activated"); c.exhale = cue('s12', 'a longer exhale');
  c.movement = cue('s12', 'and movement'); c.shutdown = cue('s12', "If you're shut down"); c.under = cue('s12', 'pull you further under');
  c.lift = cue('s12', 'You need a gentle'); c.rhythm = cue('s12', 'a rhythm');
  // s13 app
  c.app = S.s13.startMs; c.mBal = cue('s13', 'Balanced is the top'); c.mAnx = cue('s13', 'Anxious and Angry');
  c.mAng = cue('s13', 'Angry are'); c.mFrz = cue('s13', 'Freeze is the bottom'); c.oneQ = cue('s13', 'And it starts');
  c.where = cue('s13', 'Where are you'); c.tSigh = cue('s13', 'Anxious leads'); c.inhales = cue('s13', 'two inhales');
  c.longEx = cue('s13', 'one long exhale'); c.tChaos = cue('s13', 'Angry leads'); c.shake = cue('s13', 'shake the heat out');
  c.tPend = cue('s13', 'Freeze leads'); c.lr = cue('s13', 'a slow left-right'); c.land = cue('s13', 'somewhere to land');
  c.tBreath = cue('s13', 'And Balanced leads'); c.fourIn = cue('s13', 'four in'); c.eightOut = cue('s13', 'eight out');
  c.stay = cue('s13', 'to help you stay');
  // s14 close
  c.close = S.s14.startMs; c.argue = cue('s14', "You can't argue"); c.work = cue('s14', 'But you can work');
  c.notice = cue('s14', 'Notice'); c.name = cue('s14', 'Name it'); c.matchT = cue('s14', 'Match the tool');
  c.tagline = cue('s15', 'Not meditation'); c.regulation = cue('s15', 'Regulation');

  // the close: a 1.3s breath after "Match the tool to the state."; the point glides home in it and
  // the wordmark rises around it as "Not meditation." begins
  T.glide = [c.tagline - 1000, c.tagline];
  T.wordmark = T.glide[1] - 150;
  T.tag = c.tagline + 250;
  T.dur = Math.ceil((V.durMs + 4200) / 100) * 100;

  // score cues shared with the picture
  T.poundBeats = []; for (let ms = c.pound; ms < c.numb - 150; ms += 430) T.poundBeats.push(ms);
  T.sonar = []; for (let ms = c.asking; ms < S.s02.endMs + 200; ms += 1600) T.sonar.push(ms);
  T.pendApex = []; for (let ms = c.lr + 400; ms < c.tBreath - 300; ms += 2000) T.pendApex.push(ms);
  return T;
})();
if (typeof module !== 'undefined') module.exports = TIMING;
